;;; chiaroscuro-theme.el --- Theme consisting of multiple themes
;;; Commentary:
;;; Code:
(load-file "~/.doom.d/themes/common/variables.el")
(load-file "~/.doom.d/themes/common/default.el")

;; load light or dark diff colors
(if (>= INDEX-CHIAROSCURO INDEX-HIGH-CONTRAST)
    (progn (load-file "~/.doom.d/themes/common/diff-middle.el"))
  (progn (load-file "~/.doom.d/themes/common/diff-light.el")))

;; dark themes start here
(if (>= INDEX-CHIAROSCURO INDEX-LOW-CHROMA)
    (load-file "~/.doom.d/themes/common/dark.el"))

(if (> INDEX-CHIAROSCURO INDEX-DEFAULT)
   (progn
     (if (eq INDEX-CHIAROSCURO INDEX-ECLIPSE)
         (load-file "~/.doom.d/themes/light/eclipse.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-CONSOLE-LIGHT)
         (load-file "~/.doom.d/themes/light/console-light.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-COLOR-CHANGE-LIGHT)
         (load-file "~/.doom.d/themes/color-changer/color-changer.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-HIGH-CONTRAST)
         (load-file "~/.doom.d/themes/light/high-contrast.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-GRAY)
         (load-file "~/.doom.d/themes/light/gray.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-LOW-CHROMA)
         (load-file "~/.doom.d/themes/dark/low-chroma.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-BLUE)
         (load-file "~/.doom.d/themes/dark/blue.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-NEON)
         (load-file "~/.doom.d/themes/dark/neon.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-CONSOLE-DARK)
         (load-file "~/.doom.d/themes/dark/console-dark.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-RED)
         (load-file "~/.doom.d/themes/dark/red.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-CASABLANCA)
         (load-file "~/.doom.d/themes/dark/casablanca.el"))
     (if (eq INDEX-CHIAROSCURO INDEX-COLOR-CHANGE-DARK)
         (load-file "~/.doom.d/themes/color-changer/color-changer.el"))

     ;; reset index
     (if (> INDEX-CHIAROSCURO number-of-themes) (setq INDEX-CHIAROSCURO 0))
     (if (< INDEX-CHIAROSCURO 0) (setq INDEX-CHIAROSCURO number-of-themes))

     (deftheme chiaroscuro)

     (custom-theme-set-faces 'chiaroscuro

(if (eq INDEX-CHIAROSCURO INDEX-HIGH-CONTRAST)
   (progn
     `(default ((t (:foreground ,text-normal :background ,background :bold t )))))
 (progn `(default ((t (:foreground ,text-normal :background ,background :bold nil ))))))

`(ac-candidate-face ((t (:foreground ,text-normal :background ,background-fringe ))))
`(ac-candidate-mouse-face ((t (:foreground ,text-normal :background ,background-fringe ))))
`(ac-completion-face ((t (:foreground ,text-normal :background ,background-fringe :bold t ))))
`(ac-selection-face ((t (:foreground ,text-normal :background ,background-fringe :bold t ))))
`(ansi-color-bold ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(bm-fringe-face ((t (:foreground ,text-normal :background unspecified ))))
`(bm-fringe-persistent-face ((t (:foreground ,text-normal :background unspecified ))))
`(bookmark-face ((t (:foreground ,text-normal :background unspecified ))))
`(comint-highlight-prompt ((t (:foreground ,text-normal :background unspecified ))))
`(company-tooltip ((t (:foreground ,text-normal :background ,background-fringe ))))
`(company-tooltip-annotation ((t (:foreground ,text-lower :background ,background-fringe ))))
`(company-tooltip-annotation-selection ((t (:foreground ,text-low :background ,background-fringe :bold nil ))))
`(company-tooltip-common ((t (:foreground ,text-normal :background ,background-fringe :bold t ))))
`(company-tooltip-scrollbar-thumb ((t (:foreground ,text-normal :background ,background-mode-line :bold nil :italic nil ))))
`(company-tooltip-scrollbar-track ((t (:foreground ,text-normal :background ,background-mode-line :bold nil :italic nil ))))
`(company-tooltip-selection ((t (:foreground ,text-normal :background ,background-fringe :bold t ))))
`(compilation-info ((t (:foreground ,text-normal :bold t :underline t ))))
`(cua-rectangle ((t (:foreground ,text-normal :background ,background-region :bold t ))))
`(custom-button ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(diff-file-header ((t (:foreground ,text-normal :background ,background-magit :bold t ))))
`(diff-header ((t (:foreground ,text-normal :background ,background-magit ))))
`(diff-hl-change ((t (:foreground "DarkSlateBlue" :background "gray13" ))))
`(diff-hl-delete ((t (:foreground "firebrick3" :background "gray13" ))))
`(diff-hl-dired-change ((t (:foreground "orange" :background "gray13" ))))
`(diff-hl-dired-delete ((t (:foreground "red" :background "gray13" ))))
`(diff-hl-dired-ignored ((t (:foreground "blue" :background "gray13" ))))
`(diff-hl-dired-insert ((t (:foreground "green" :background "gray13" ))))
`(diff-hl-dired-unknown ((t (:foreground "gray" :background "gray13" ))))
`(diff-hl-insert ((t (:foreground "SeaGreen" :background "gray13" ))))
`(diff-hl-reverted-hunk-highlight ((t (:foreground ,text-normal :background "gray13" ))))
`(dired-directory ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(dired-header ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(dired-ignored ((t (:foreground ,text-normal :background unspecified ))))
`(dired-mark ((t (:foreground ,text-normal :background unspecified ))))
`(dired-marked ((t (:foreground ,text-normal :background unspecified ))))
`(dired-narrow-blink ((t (:foreground ,text-normal :background unspecified ))))
`(dired-perm-write ((t (:foreground ,text-normal :background unspecified ))))
`(dired-set-id ((t (:foreground ,text-normal :background unspecified ))))
`(dired-special ((t (:foreground ,text-normal ))))
`(dired-symlink ((t (:foreground ,text-normal :background unspecified ))))
`(dired-warning ((t (:foreground ,text-normal :background unspecified ))))
`(direded-flagged ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-autofile-name ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-compressed-file-name ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-compressed-file-suffix ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-date-time ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-deletion ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-deletion-file-name ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-dir-heading ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-dir-name ((t (:foreground ,text-type :background unspecified :bold t ))))
`(diredfl-dir-priv ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-exec-priv ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-executable-tag ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-file-name ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-file-suffix ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-flag-mark ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-flag-mark-line ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-ignored-file-name ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-link-priv ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-no-priv ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-number ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-other-priv ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-rare-priv ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-read-priv ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-symlink ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-tagged-autofile-name ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-write-priv ((t (:foreground ,text-normal :background unspecified ))))
`(doom-dashboard-banner ((t (:foreground ,text-low :background unspecified :bold nil ))))
`(doom-dashboard-footer ((t (:foreground ,text-low :background unspecified ))))
`(doom-dashboard-footer ((t (:foreground ,text-low :background unspecified ))))
`(doom-dashboard-loaded ((t (:foreground ,text-low :background unspecified ))))
`(doom-dashboard-menu ((t (:foreground ,text-low :background unspecified ))))
`(doom-dashboard-menu-title ((t (:foreground ,text-low :background unspecified ))))
`(doom-modeline ((t (:background ,background-mode-line :bold nil :box nil ))))
`(doom-modeline-bar ((t (:foreground ,text-normal :background ,background-mode-line :bold nil :box nil ))))
`(doom-modeline-bar-inactive ((t (:foreground ,text-normal :background ,background-mode-line :bold nil :box nil ))))
`(doom-modeline-battery-charging ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-battery-critical ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-battery-error ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-battery-full ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-battery-normal ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-battery-warning ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-boon-command-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-boon-insert-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-boon-off-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-boon-special-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-buffer-file ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-buffer-major-mode ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-buffer-minor-mode ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-buffer-modified ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-buffer-path ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-buffer-timemachine ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-compilation ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-debug ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-debug-visual ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-emphasis ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-evil-emacs-state ((t (:foreground "magenta3" :background "magenta" :bold nil))))
`(doom-modeline-evil-insert-state ((t (:foreground "red3" :background "red" :bold nil))))
`(doom-modeline-evil-motion-state ((t (:foreground "blue3" :background "blue" :bold nil))))
`(doom-modeline-evil-normal-state ((t (:foreground "green3" :background "green" :bold nil))))
`(doom-modeline-evil-operator-state ((t (:foreground "gray3" :background "gray" :bold nil))))
`(doom-modeline-evil-replace-state ((t (:foreground "orange3" :background "orange" :bold nil))))
`(doom-modeline-evil-user-state ((t (:foreground "black" :background "black" :bold nil))))
`(doom-modeline-evil-visual-state ((t (:foreground "yellow3" :background "yellow" :bold nil))))
`(doom-modeline-fly-insert-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-fly-normal-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-god ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-highlight ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-host ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-info ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-input-method ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-input-method-alt ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-lsp-error ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-lsp-running ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-lsp-success ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-lsp-warning ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-meow-beacon-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-meow-insert-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-meow-keypad-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-meow-motion-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-meow-normal-state ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-notification ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-overwrite ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-panel ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-persp-buffer-not-in-persp ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-persp-name ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-project-dir ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-project-parent-dir ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-project-root-dir ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-repl-success ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-repl-warning ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-ryo ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-time ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-unread-number ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-urgent ((t (:foreground ,text-normal :background ,background-mode-line :bold nil))))
`(doom-modeline-warning ((t (:foreground ,text-normal :background ,background-mode-line :bold))))
`(ediff-current-diff-A ((t (:foreground "#000000" :background ,background-diff-current-A ))))
`(ediff-current-diff-Ancestor ((t (:foreground "#000000" :background ,background-diff-current-Ancestor ))))
`(ediff-current-diff-B ((t (:foreground "#000000" :background ,background-diff-current-B ))))
`(ediff-current-diff-C ((t (:foreground "#000000" :background ,background-diff-current-C ))))
`(ediff-even-diff-A ((t (:foreground "#000000" :background ,background-diff-even-A ))))
`(ediff-even-diff-Ancestor ((t (:foreground "#000000" :background ,background-diff-even-Ancestor ))))
`(ediff-even-diff-B ((t (:foreground "#000000" :background ,background-diff-even-B ))))
`(ediff-even-diff-C ((t (:foreground "#000000" :background ,background-diff-even-C ))))
`(ediff-fine-diff-A ((t (:foreground "#000000" :background ,background-diff-fine-A ))))
`(ediff-fine-diff-Ancestor ((t (:foreground "#000000" :background ,background-diff-fine-Ancestor ))))
`(ediff-fine-diff-B ((t (:foreground "#000000" :background ,background-diff-fine-B ))))
`(ediff-fine-diff-C ((t (:foreground "#000000" :background ,background-diff-fine-C ))))
`(ediff-odd-diff-A ((t (:foreground "#000000" :background ,background-diff-odd-A ))))
`(ediff-odd-diff-Ancestor ((t (:foreground "#000000" :background ,background-diff-odd-Ancestor ))))
`(ediff-odd-diff-B ((t (:foreground "#000000" :background ,background-diff-odd-B ))))
`(ediff-odd-diff-C ((t (:foreground "#000000" :background ,background-diff-odd-C ))))
`(eglot-diagnostic-tag-unnecessary-face ((t (:foreground ,text-warning :background unspecified :bold t ))))
`(eglot-mode-line ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(elfeed-log-date-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-log-debug-level-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-log-error-level-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-log-info-level-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-log-warn-level-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-date-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-feed-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-filter-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-last-update-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-tag-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-title-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-unread-count-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-unread-title-face ((t (:foreground ,text-normal :background unspecified ))))
`(eshell-ls-directory ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(eshell-prompt ((t (:foreground ,text-normal :background unspecified ))))
`(evil-ex-lazy-highlight ((t (:foreground ,text-normal :background unspecified ))))
`(evil-ex-search ((t (:foreground ,text-normal :background unspecified ))))
`(evil-ex-substitute-matches ((t (:foreground ,text-normal :background unspecified ))))
`(eww-form-checkbox ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-form-select ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-form-submit ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-form-text ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-form-textarea ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-valid-certificate ((t (:foreground ,text-normal :background ,background-mode-line :bold t ))))
`(flycheck-error ((t (:foreground ,text-normal :bold t :underline t ))))
`(flycheck-error-list-checker-name ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-column-number ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-error ((t (:foreground ,text-normal :bold t :underline t ))))
`(flycheck-error-list-error-message ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-filename ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-highlight ((t (:foreground ,text-normal :bold t :underline t ))))
`(flycheck-error-list-id ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-id-with-explainer ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-info ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-line-number ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-warning ((t (:foreground ,text-warning :bold t ))))
`(flycheck-fringe-error ((t (:foreground ,text-normal :bold t ))))
`(flycheck-fringe-info ((t (:foreground ,text-normal :bold t ))))
`(flycheck-fringe-warning ((t (:foreground ,text-warning :bold t ))))
`(focus-unfocused ((t (:foreground ,text-lower ))))
`(font-lock-bracket-face ((t (:foreground ,text-normal ))))
`(font-lock-builtin-face ((t (:foreground ,text-type :bold t ))))
`(font-lock-comment-delimiter-face ((t (:foreground ,text-comment ))))
`(font-lock-comment-face ((t (:foreground ,text-comment ))))
`(font-lock-constant-face ((t (:foreground ,text-constant ))))
`(font-lock-doc-face ((t (:foreground ,text-comment ))))
`(font-lock-function-call-face ((t (:foreground ,text-normal ))))
`(font-lock-function-name-face ((t (:foreground ,text-function :bold t ))))
`(font-lock-keyword-face ((t (:foreground ,text-keyword :bold t ))))
`(font-lock-number-face ((t (:foreground ,text-normal ))))
`(font-lock-preprocessor-face ((t (:foreground ,text-preprocessor ))))
`(font-lock-regexp-face ((t (:foreground ,text-normal :bold t ))))
`(font-lock-regexp-grouping-backslash ((t (:foreground ,text-normal ))))
`(font-lock-regexp-grouping-construct ((t (:foreground ,text-normal ))))
`(font-lock-string-face ((t (:foreground ,text-low ))))
`(font-lock-type-face ((t (:foreground ,text-type :bold t ))))
`(font-lock-variable-name-face ((t (:foreground ,text-variable ))))
`(font-lock-variable-use-face ((t (:foreground ,text-variable ))))
`(fringe ((t (:foreground ,text-normal :background ,background-fringe ))))
`(header-line ((t (:foreground ,text-normal ))))
`(helm-M-x-key ((t (:foreground ,text-match-1 ))))
`(helm-bookmark-directory ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(helm-bookmark-file ((t (:foreground ,text-normal ))))
`(helm-buffer-directory ((t (:foreground ,text-normal :bold t ))))
`(helm-buffer-file ((t (:foreground ,text-normal :background unspecified ))))
`(helm-buffer-saved-out ((t (:foreground ,text-normal ))))
`(helm-candidate-number ((t (:foreground ,text-normal ))))
`(helm-ff-directory ((t (:foreground ,text-normal :bold t ))))
`(helm-ff-dotted-directory ((t (:foreground ,text-low :background unspecified ))))
`(helm-ff-executable ((t (:foreground ,text-normal :background unspecified ))))
`(helm-ff-file-extension ((t (:foreground ,text-low :background unspecified :bold nil ))))
`(helm-ff-prefix ((t (:foreground ,text-normal :background unspecified ))))
`(helm-ff-rsync-progress ((t (:foreground ,text-normal ))))
`(helm-grep-file ((t (:foreground ,text-normal :background unspecified :bold t :underline t ))))
`(helm-grep-finish ((t (:foreground ,text-normal :background unspecified ))))
`(helm-grep-lineno ((t (:foreground ,text-low ))))
`(helm-grep-match ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(helm-lsp-diag-error ((t (:foreground ,text-error :bold t :underline t ))))
`(helm-lsp-diag-info ((t (:foreground ,text-error :bold t :underline t ))))
`(helm-match ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(helm-match-item ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(helm-minibuffer-prompt ((t (:foreground ,text-normal :background unspecified ))))
`(helm-non-file-buffer ((t (:foreground ,text-lower :background unspecified :italic t ))))
`(helm-selection ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(helm-selection-line ((t (:foreground ,text-match-2 :background ,background-match-1 :bold t ))))
`(helm-separator ((t (:foreground ,text-low :background ,background-hl ))))
`(helm-source-header ((t (:foreground ,text-normal :background unspecified :bold t :height 1.3 :family "Sans Serif" ))))
`(helm-swoop-target-line-block-face ((t (:foreground ,text-hl :background unspecified ))))
`(helm-swoop-target-line-face ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(helm-swoop-target-word-face ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(help-key-binding ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(highlight ((t (:foreground ,text-normal :background unspecified ))))
`(hl-line ((t (:foreground ,text-hl :background ,background :bold t ))))
`(hydra-face-blue ((t (:foreground ,text-normal :bold t ))))
`(hydra-face-red ((t (:foreground ,text-normal :bold t ))))
`(ido-first-match ((t (:foreground ,text-match-1 :background ,background-hl ))))
`(ido-only-match ((t (:foreground ,text-match-1 :background ,background-hl ))))
`(ido-subdir ((t (:foreground ,text-normal ))))
`(iedit-occurrence ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(info-menu-star ((t (:foreground ,text-normal :background unspecified ))))
`(info-node ((t (:foreground ,text-normal :background unspecified :bold t :italic t ))))
`(info-xref ((t (:foreground ,text-link :background unspecified :underline t ))))
`(info-xref-visited ((t (:foreground ,text-low :background unspecified :underline t ))))
`(isearch ((t (:foreground ,text-normal :background unspecified ))))
`(ivy-current-match ((t (:foreground ,text-highlight-1 :background ,background :bold t ))))
`(ivy-grep-info ((t (:foreground ,text-normal :background unspecified ))))
`(ivy-grep-line-number ((t (:foreground ,text-normal :background unspecified ))))
`(ivy-match-required-face ((t (:foreground ,text-normal :background unspecified ))))
`(ivy-minibuffer-match-face-1 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(ivy-minibuffer-match-face-2 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(ivy-minibuffer-match-face-3 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(ivy-minibuffer-match-face-4 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(ivy-modified-buffer ((t (:foreground ,text-low :background unspecified :bold t :italic t ))))
`(ivy-modified-outside-buffer ((t (:foreground ,text-low :background unspecified :bold t :italic t ))))
`(ivy-org ((t (:foreground ,text-low :background unspecified :italic t ))))
`(ivy-subdir ((t (:bold t ))))
`(ivy-virtual ((t (:foreground ,text-lower ))))
`(lazy-highlight ((t (:foreground ,text-normal :background unspecified ))))
`(lazy-highlight ((t (:foreground ,text-normal :background unspecified ))))
`(line-number ((t (:foreground ,text-line-number :background unspecified ))))
`(line-number-current-line ((t (:foreground ,text-line-number :background unspecified :bold t ))))
`(line-number-major-tick ((t (:foreground ,text-line-number :background unspecified ))))
`(line-number-minor-tick ((t (:foreground ,text-line-number :background unspecified ))))
`(link ((t (:foreground ,text-normal :underline t ))))
`(lsp-face-highlight-read ((t (:foreground ,text-function :background unspecified :bold t ))))
`(lsp-face-highlight-write ((t (:foreground ,text-function :background unspecified :bold t ))))
`(lsp-flycheck-warning-unnecessary-face ((t (:foreground ,text-warning :bold t :underline t ))))
`(magit-blame-heading ((t (:foreground ,text-normal :background ,background-fringe ))))
`(magit-blame-highlight ((t (:foreground ,text-normal :background ,background-fringe ))))
`(magit-blame-margin ((t (:foreground ,text-normal :background ,background-fringe ))))
`(magit-branch-current ((t (:foreground ,text-normal :background unspecified :bold t :box (:line-width 1 :color ,text-normal) ))))
`(magit-branch-local ((t (:foreground ,text-normal :background unspecified :bold t :box (:line-width 1 :color ,text-normal) ))))
`(magit-branch-remote ((t (:foreground ,text-normal :background unspecified :bold t :box (:line-width 1 :color ,text-normal) ))))
`(magit-branch-remote-head ((t (:foreground ,text-normal :background unspecified :bold t :box (:line-width 1 :color ,text-normal) :bold t :italic t ))))
`(magit-branch-upstream ((t (:foreground ,text-normal :background unspecified :bold t :box (:line-width 1 :color ,text-normal) ))))
`(magit-diff-conflict-heading ((t (:foreground ,text-normal :background ,background-magit ))))
`(magit-diff-context ((t (:foreground ,text-lower :background unspecified ))))
`(magit-diff-context-highlight ((t (:foreground ,text-normal :background ,background-magit-dark ))))
`(magit-diff-file-heading ((t (:foreground ,text-lower :background unspecified :bold t ))))
`(magit-diff-file-heading-highlight ((t (:foreground ,text-normal :background ,background-magit :bold t ))))
`(magit-diff-file-heading-selection ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(magit-diff-hunk-heading ((t (:foreground ,text-low :background ,background-magit ))))
`(magit-diff-hunk-heading-highlight ((t (:foreground ,text-normal :background ,background-magit ))))
`(magit-diff-hunk-heading-selection ((t (:foreground ,text-normal :background ,background-magit ))))
`(magit-hash ((t (:foreground ,text-low ))))
`(magit-header-line ((t (:foreground ,text-normal :bold t ))))
`(magit-header-line-key ((t (:foreground ,text-normal :bold t ))))
`(magit-keyword-squash ((t (:foreground ,text-normal ))))
`(magit-log-author ((t (:foreground ,text-low ))))
`(magit-log-date ((t (:foreground ,text-low ))))
`(magit-reflog-amend ((t (:foreground ,text-normal ))))
`(magit-reflog-checkout ((t (:foreground ,text-normal ))))
`(magit-reflog-cherry-pick ((t (:foreground ,text-normal ))))
`(magit-reflog-commit ((t (:foreground ,text-normal ))))
`(magit-reflog-merge ((t (:foreground ,text-normal ))))
`(magit-reflog-other ((t (:foreground ,text-normal ))))
`(magit-reflog-rebase ((t (:foreground ,text-normal ))))
`(magit-reflog-remote ((t (:foreground ,text-normal ))))
`(magit-reflog-reset ((t (:foreground ,text-normal ))))
`(magit-section-heading ((t (:foreground ,text-low :bold t ))))
`(magit-section-highlight ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(magit-sequence-head ((t (:foreground ,text-normal :bold t ))))
`(match ((t (:foreground ,text-match-1 :background ,background :bold t ))))
`(message-header-cc ((t (:foreground ,text-normal ))))
`(message-header-name ((t (:foreground ,text-normal ))))
`(message-header-newsgroups ((t (:foreground ,text-normal ))))
`(message-header-other ((t (:foreground ,text-normal ))))
`(message-header-subject ((t (:foreground ,text-normal ))))
`(message-header-to ((t (:foreground ,text-normal ))))
`(minibuffer-prompt ((t (:foreground ,text-normal :background unspecified ))))
`(mode-line ((t (:background ,background-mode-line :box (:line-width 8 :color ,background-mode-line) ))))
`(mode-line-buffer-id ((t (:bold t ))))
`(mode-line-highlight ((t (:background ,background-mode-line))))
`(mode-line-inactive ((t (:background ,background-mode-line :box (:line-width 8 :color ,background-mode-line) ))))
`(org-agenda-column-dateline ((t (:foreground ,text-normal :underline t ))))
`(org-agenda-date ((t (:foreground ,text-low :bold t ))))
`(org-agenda-date-today ((t (:foreground ,text-normal :bold t :italic t ))))
`(org-agenda-date-weekend ((t (:foreground ,text-lower :bold t ))))
`(org-agenda-diary ((t (:foreground ,text-normal ))))
`(org-agenda-dimmed-todo-face ((t (:foreground ,text-low ))))
`(org-agenda-done ((t (:foreground ,text-lower :background unspecified ))))
`(org-agenda-filter-category ((t (:foreground ,text-normal ))))
`(org-agenda-filter-effort ((t (:foreground ,text-normal ))))
`(org-agenda-filter-regexp ((t (:foreground ,text-normal ))))
`(org-agenda-filter-tags ((t (:foreground ,text-normal ))))
`(org-agenda-restriction-lock ((t (:foreground ,text-normal ))))
`(org-agenda-structure ((t (:foreground ,text-low ))))
`(org-archived ((t (:foreground ,text-normal :background unspecified ))))
`(org-block ((t (:foreground ,text-normal :background unspecified :italic t ))))
`(org-block-begin-line ((t (:foreground ,text-lower :background unspecified ))))
`(org-block-end-line ((t (:foreground ,text-lower :background unspecified ))))
`(org-checkbox-statistics-done ((t (:foreground ,text-low :background unspecified ))))
`(org-column ((t (:foreground ,text-normal :background unspecified ))))
`(org-column-title ((t (:foreground ,text-normal :background unspecified ))))
`(org-date-selected ((t (:foreground ,text-normal :background ,background-hl ))))
`(org-document-info ((t (:foreground ,text-normal :background unspecified ))))
`(org-document-info-keyword ((t (:foreground ,text-normal :background unspecified ))))
`(org-document-title ((t (:foreground ,text-normal :background unspecified ))))
`(org-done ((t (:foreground ,text-lower :bold t ))))
`(org-drawer ((t (:foreground ,text-normal :background unspecified ))))
`(org-ellipsis ((t (:foreground ,text-normal :background unspecified ))))
`(org-footnote ((t (:foreground ,text-normal :background unspecified ))))
`(org-formula ((t (:foreground ,text-normal :background unspecified ))))
`(org-headline-done ((t (:foreground ,text-low :background unspecified ))))
`(org-headline-todo ((t (:foreground ,text-normal :background unspecified ))))
`(org-hide ((t (:foreground ,text-normal :background unspecified ))))
`(org-imminent-deadline ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(org-latex-and-related ((t (:foreground ,text-normal :background unspecified ))))
`(org-link ((t (:foreground ,text-link :background unspecified :bold t :underline t ))))
`(org-list-dt ((t (:foreground ,text-normal :background unspecified ))))
`(org-macro ((t (:foreground ,text-normal :background unspecified ))))
`(org-meta-line ((t (:foreground ,text-normal :background unspecified ))))
`(org-property-value ((t (:foreground ,text-normal :background unspecified ))))
`(org-quote ((t (:foreground ,text-normal :background unspecified :italic t ))))
`(org-scheduled ((t (:foreground ,text-normal :background unspecified ))))
`(org-sexp-date ((t (:foreground ,text-normal :background unspecified ))))
`(org-tag-group ((t (:foreground ,text-normal :background unspecified ))))
`(org-target ((t (:foreground ,text-normal :background unspecified :underline t ))))
`(org-time-grid ((t (:foreground ,text-normal :background unspecified ))))
`(org-upcoming-deadline ((t (:foreground ,text-low :background unspecified ))))
`(org-upcoming-distant-deadline ((t (:foreground ,text-lower :background unspecified ))))
`(popup-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-isearch-match ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-menu-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-menu-mouse-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-menu-selection-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-menu-summary-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-scroll-bar-background-face ((t (:foreground ,text-normal :background ,background-mode-line :bold nil :italic nil ))))
`(popup-scroll-bar-foreground-face ((t (:foreground ,text-normal :background ,background-mode-line :bold nil :italic nil ))))
`(popup-summary-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-tip-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(region ((t (:foreground ,text-region :background ,background-region ))))
`(secondary-selection ((t (:foreground ,text-normal :background unspecified ))))
`(show-paren-match ((t (:foreground ,background :background ,text-highlight-2 :bold t :underline t ))))
`(shr-link ((t (:foreground ,text-link :background ,background :underline t ))))
`(speed-type-correct ((t (:foreground ,text-lower ))))
`(speed-type-default ((t (:foreground ,text-normal ))))
`(speed-type-mistake ((t (:foreground ,background-diff-current-A ))))
`(swiper-background-match-1-face-1 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-background-match-1-face-2 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-background-match-1-face-3 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-background-match-1-face-4 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-line-face ((t (:foreground ,text-highlight-1 :background ,background-match-1 :bold t ))))
`(swiper-match-face-1 ((t (:foreground "red" :background ,background-match-1 :bold t ))))
`(swiper-match-face-2 ((t (:foreground "orange" :background ,background-match-1 :bold t ))))
`(swiper-match-face-3 ((t (:foreground "yellow" :background ,background-match-1 :bold t ))))
`(swiper-match-face-4 ((t (:foreground "green" :background ,background-match-1 :bold t ))))
`(tab-bar ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(tab-bar-tab ((t (:foreground ,text-normal :background ,background-mode-line :bold t :box (:line-width 8 :color ,background-mode-line) ))))
`(tab-bar-tab-group-current ((t (:foreground ,text-normal :background unspecified ))))
`(tab-bar-tab-group-inactive ((t (:foreground ,text-normal :background unspecified ))))
`(tab-bar-tab-inactive ((t (:foreground ,text-normal :background ,background-mode-line :box (:line-width 8 :color ,background-mode-line) ))))
`(tab-bar-tab-ungrouped ((t (:foreground ,text-normal :background unspecified ))))
`(tab-line ((t (:foreground ,text-normal :background unspecified ))))
`(transient-key-exit ((t (:foreground ,text-normal :bold t ))))
`(transient-key-return ((t (:foreground ,text-normal :bold t ))))
`(transient-key-stay ((t (:foreground ,text-normal :bold t ))))
`(transient-red ((t (:foreground ,text-normal :background unspecified ))))
`(treemacs-directory-collapsed-face ((t (:foreground ,text-low :background unspecified ))))
`(treemacs-directory-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(treemacs-file-face ((t (:foreground ,text-normal :background unspecified ))))
`(treemacs-fringe-indicator-face ((t (:foreground ,background-mode-line :background unspecified :bold t ))))
`(treemacs-git-added-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(treemacs-git-ignored-face ((t (:foreground ,text-low :background unspecified :bold t ))))
`(treemacs-git-modified-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(treemacs-git-renamed-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(treemacs-git-untracked-face ((t (:foreground ,text-low :background unspecified :bold t ))))
`(treemacs-root-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(vertical-border ((t (:foreground ,background ))))
`(whitespace-line ((t (:background unspecified ))))
`(whitespace-newline ((t (:foreground ,text-whitespace :background unspecified ))))
`(whitespace-space ((t (:foreground ,text-whitespace :background unspecified ))))
`(window-divider ((t (:foreground ,background ))))
`(window-divider-firt-pixel ((t (:foreground ,background ))))
`(window-divider-last-pixel ((t (:foreground ,background ))))
`(xref-match ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(ztreep-diff-model-add-face ((t (:foreground ,text-normal :background unspecified ))))
`(ztreep-diff-model-normal-face ((t (:foreground ,text-normal :background unspecified ))))
)))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'chiaroscuro)

;;; chiaroscuro-theme.el ends here
